# Site settings
title: "Eduardo Palhares"
email: xeduardopalhares@gmail.com
description: "Site pessoal de Eduardo Palhares."
baseurl: ""
url: ""
title_description:
  "Olá sou um estudante autodidata com uma paixão por tecnologia
  inovadora que atualmente se concentra no estudo de Python e JavaScript,
  incluindo o ecossistema ao redor dessas linguagens.<br>
  Todos os dias fazendo algo diferente e procurando aprender coisas novas."
title_image: "https://media.licdn.com/dms/image/C4D03AQFbj_6aKSKA8Q/profile-displayphoto-shrink_200_200/0?e=1555545600&v=beta&t=kifDepzf5KzngyG4LDUG9DscFEOyvgR_xG7wy3yxC1c"
google_analytics: ""
disqus_account: disqus_3SWn8SuP5V
github_repository: https://github.com/palharez/palharez.github.io
addthis_id:
post_limit: 5

# Social usernames/URLs
twitter_username: xeduardopjr
github_username: palharez
instagram_username: eduardoapjr
reddit_username:
linkedin_link: http://linkedin.com/in/eduardopalhares
google_plus_link:
stackoverflow_link:
xing_link:
facebook_link: http://facebook.com/xEduardoPalhares

# Footer
footer_left: 'Modified with <i class="fa fa-heart"></i> by <a href="https://twitter.com/xeduardopjr">Palharez</a>'
footer_right: '&lt;/&gt; on <a href="https://github.com/jacobtomlinson/carte-noire">Github</a> &nbsp;<i class="fa fa-github-alt"></i>'

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
