# Site settings
title: "Palharez"
email:  xeduardopalhares@gmail.com
description: "Meu site pessoal."
baseurl: ""
url: ""
title_description: "Olá me chamo Eduardo Palhares, um estudante autodidata apaixonado por programação, 
                    nasci e vivo em São Paulo/SP, atualmente focado em estudar Python e JavaScript, 
                    incluindo o ecossistema ao redor dessas linguagens.<br>
                    Cada dia fazendo algo diferente e procurando aprender algo novo!"
title_image: "https://pbs.twimg.com/profile_images/936002333091254272/RTDIK_2__400x400.jpg"
google_analytics: ""
disqus_account: 
github_repository: 
addthis_id: 
post_limit: 5

# Social usernames/URLs
twitter_username: xeduardopjr
github_username:  palharez
instagram_username: eduardoapjr
reddit_username: 
linkedin_link: http://linkedin.com/in/eduardopalhares
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: http://facebook.com/xEduardoPalhares

# Footer
footer_left: "Modified with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/xeduardopjr\">Eduardo Palhares</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
