# Site settings
title: "Eduardo Palhares"
email:  xeduardopalhares@gmail.com
description: "A dark blog theme for Jekyll."
baseurl: ""
url: "http://carte-noire.jacobtomlinson.co.uk/"
title_description: "A dark blog theme for Jekyll focusing on a clear reading experience. Large text and a narrow body makes carte noire a gorgeous read. With excellent code snippet support and integrated tools such as AddThis and Disqus giving your Jekyll blog all the functionality your users expect."
title_image: "https://pbs.twimg.com/profile_images/936002333091254272/RTDIK_2__400x400.jpg"
google_analytics: "UA-20365477-4"
disqus_account: cartenoire
github_repository: https://github.com/jacobtomlinson/carte-noire
addthis_id: ra-513c6fa83da6ec67
post_limit: 5

# Social usernames/URLs
twitter_username: xeduardopjr
github_username:  palharez
instagram_username: eduardoapjr
reddit_username: 
linkedin_link: http://linkedin.com/in/eduardopalhares
google_plus_link: 
stackoverflow_link: 
xing_link:
facebook_link: http://facebook.com/xEduardoPalhares

# Footer
footer_left: "Modified with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/xeduardopjr\">Eduardo Palhares</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
